import Navbar from '@/components/shared/Navbar'
import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-50' >
        <Navbar />
        <div className="section pt-[100px] px-[5px] ">
          {children}
        </div>
      </body>
    </html>
  )
}
